### ISSUE TITLE
Compilation errors in ESPHome

### ISSUE THREAD

**Issue by rikman122** [Bunicutz/ESP32_Midea_RS485#1]
Hi mate,

I'm trying to test your integration in Home Assistant but I can't get it to compile.

My configuration in ESPHome:

[midea-ac.txt](https://github.com/Bunicutz/ESP32_Midea_RS485/files/9270030/midea-ac.txt)

And the error logs while compiling:

![image](https://user-images.githubusercontent.com/47759423/183113567-cb79eb5d-ef0b-4a84-aae8-e2ac26f9fd5a.png)

[logs_midea-ac_upload.txt](https://github.com/Bunicutz/ESP32_Midea_RS485/files/9270012/logs_midea-ac_upload.txt)

Do you know what's happening? Maybe it's something related with I'm using NodeMCU ESP8266 rather than ESP32?

Thank you for your work

**Comment by rikman122** [comment]
It was definitely an error caused for trying to flash an ESP8266... I'm working on a port of your code for the ESP8266 boards and will let you know when it's done. Of course will give you credits.

Kind Regards

**Comment by Bunicutz** [comment]
Hello,

Just got your message.

Never tried it on ESP8266 and glad to hear somebody will port it.
I can give some advice. For ESP8266 try using just Serial or Serial1 instead of Serial2 and change the parameters for begin. 

![image](https://user-images.githubusercontent.com/99245025/183130263-6183316c-37c1-42a3-a686-218800a10a9d.png)

If interested you can read more at:
http://arduino.esp8266.com/Arduino/versions/2.3.0/doc/reference.html (I hope is up to date)
